Numpy es para trabajar con matemáticas a gran velocidad
Trabaja con:
- ndarray (n-dimensional array)
- Matrices
- Estadística
- Vectorización matemática

Introducción a los arrays

In [ ]:
#Crear un array
import numpy as np
array = np.array([1,2,3,4,5], dtype=float)
#OJO: Todos los tipos iguales, operaciones básicas directamente con su simbolo, filas iguales
#dtype para indicar el tipo
print(array)
print(array.ndim)#mostrar dimensiones
print(array.shape)#mostrar forma
print(array.size)#mostrar tamaño
print(array.dtype)#mostrar tipo

b = np.zeros((5, 5), dtype=int) #Array de ceros
print(b)
#OJO: para poner arrays multidimensionales, poner valores en tuplas
#OJO: el orden va en z, y, x
c = np.ones((5, 5), dtype=int) #Array de unos
print(c)
d = np.empty((5, 5), dtype=int) #Array vacío
print(d)
e = np.arange(5, 10, 2) #Array con valores consecutivos enteros positivos
#OJO: inicio, fin, pasos
print(e)
f = np.linspace(0, 1, 5) #Array con x valores entre 0 y 1 en este caso
print(f)



[1. 2. 3. 4. 5.]
1
(5,)
5
float64
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[      117169862               0 134033318907728 134033319446016
         11657312]
 [       11657248        11795736        11819912        11795784
  134033332893936]
 [134033319262768        11596960        11805096 134033332895088
  134033319262896]
 [134033339299664        11807376 134033332894640 134033319575664
  134033319575792]
 [      116411392 134033319567696 134033319469216 134033339424448
              208]]
[5 7 9]
[0.   0.25 0.5  0.75 1.  ]


Operaciones con arrays 1:

In [ ]:
np.sort(b) #Ordenar array ascendentemente
np.concatenate((b, c)) #Unir dos arrays
#OJO: ponerlo en dos paréntesis

g = np.concatenate((b, c), axis=0)
h = np.concatenate((b, c), axis=1)
print(g)
print(h)
#OJO: axis se refiere al eje en el que está

print(g.size)
i = np.reshape(g, shape=(5, 5, 2), order='C')
print(i)
#Cambiar la forma, OJO: comprobar size porque tiene que haber el mismo numero de elementos
#Array, forma y orden(F o C, dependiendo si por columnas o por filas(Fortran o C))




[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]]
50
[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]]


Operaciones con arrays 2: 

In [ ]:
a = np.array([1, 2, 3])
a2 = a[np.newaxis, :] #Añadir un nuevo eje
#OJO: dependiendo de donde este la coma, se añade en un eje u otro
print(a)
b = np.expand_dims(a, axis=1)
print(b)
c = np.expand_dims(a, axis=0)
print(c)
#OJO, dependiendo del eje, se amplia de una forma u otra, ojo

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]


Slicing

In [ ]:
print(a[0])
print(a[0:2])
#OJO: si no se pone nada, se da por hecho que es hasta el inicio/final
#OJO: en negativo se cuenta desde el final sin contar el 0
print(a[-1])
print(a[:1])

#Hacer operaciones lógicas
print(a[a>1])

#Comprobar que los valores no son cero o false
print(np.nonzero(a))
#OJO: te devuelve una lista con cada coordenada de los valores que no son cero o false
print(np.isnan(a))
#En todo el array, marca falso si no es NaN y si es verdadero, es porque no hay

1
[1 2]
3
[1]
[2 3]
(array([0, 1, 2]),)
[False False False]
